--JEUX DE DONNEES LANGUE--
INSERT INTO LANGUE (code, nom_langue) VALUES
( 'FR', 'Français'),
( 'EN', 'Anglais'),
( 'ES', 'Espagnol'),
( 'DE', 'Allemand'),
( 'IT', 'Italien'),
( 'PT', 'Portugais'),
( 'RU', 'Russe'),
( 'ZH', 'Chinois (Mandarin)'),
('JA', 'Japonais'),
( 'KO', 'Coréen'),
( 'AR', 'Arabe'),
( 'HI', 'Hindi'),
('BE', 'Bengali'),
( 'PA', 'Punjabi'),
( 'UR', 'Ourdou'),
( 'TR', 'Turc'),
( 'PL', 'Polonais'),
( 'NL', 'Néerlandais'),
( 'SV', 'Suédois'),
( 'NO', 'Norvégien'),
( 'DA', 'Danois'),
( 'FI', 'Finnois'),
( 'CS', 'Tchèque'),
( 'EL', 'Grec'),
( 'HE', 'Hébreu'),
( 'TH', 'Thaïlandais'),
( 'ID', 'Indonésien'),
( 'MS', 'Malais'),
( 'VI', 'Vietnamien'),
( 'SW', 'Swahili');

--JEUX DE DONNEES CATEGORIE--
INSERT INTO CATEGORIE (id_categorie, genre) VALUES
(1, "Action"),
(2, "Aventure"),
(3, "Comédie"),
(4, "Drame"),
(5, "Science-fiction"),
(6, "Fantastique"),
(7, "Horreur"),
(8, "Thriller"),
(9, "Romance"),
(10, "Animation"),
(11, "Documentaire"),
(12, "Policier"),
(13, "Historique"),
(14, "Musical"),
(15, "Mystère"),
(16, "Guerre"),
(17, "Western"),
(18, "Familial"),
(19, "Biographique"),
(20, "Sport"),
(21, "Crime"),
(22, "Anecdote"),
(23, "Film noir"),
(24, "Fantasy"),
(25, "Epouvante"),
(26, "Suspense"),
(27, "Parodie"),
(28, "Satire"),
(29, "LGBTQ+"),
(30, "Drame psychologique");



--JEUX DE DONNEES SPECTATEURS--
INSERT INTO SPECTATEUR (id_spectateur, nom, prenom, age, sexe) VALUES
(1, "Dupond", "Jean", 15, "Homme"),
(2, "Martin", "Claire", 16, "Femme"),
(3, "Lemoine", "Paul", 17, "Homme"),
(4, "Durand", "Sophie", 18, "Femme"),
(5, "Moreau", "Luc", 19, "Homme"),
(6, "Lefevre", "Isabelle", 20, "Femme"),
(7, "Roux", "Michel", 21, "Homme"),
(8, "Perrin", "Juliette", 22, "Femme"),
(9, "Gauthier", "Pierre", 23, "Homme"),
(10, "Clement", "Nathalie", 24, "Femme"),
(11, "Meyer", "Jean-Pierre", 25, "Homme"),
(12, "Bernard", "Chantal", 26, "Femme"),
(13, "Simon", "Jacques", 27, "Homme"),
(14, "Barre", "Elise", 28, "Femme"),
(15, "Boucher", "Thomas", 29, "Homme"),
(16, "Robert", "Emilie", 30, "Femme"),
(17, "Joly", "Victor", 31, "Homme"),
(18, "Benoit", "Aline", 32, "Femme"),
(19, "Lemoine", "Marc", 33, "Homme"),
(20, "Fournier", "Carole", 34, "Femme"),
(21, "Thomas", "Antoine", 35, "Homme"),
(22, "Vincent", "Sabrina", 36, "Femme"),
(23, "Leclerc", "Denis", 37, "Homme"),
(24, "Lemoine", "Sandrine", 38, "Femme"),
(25, "Brunet", "Georges", 39, "Homme"),
(26, "Chauvin", "Mélanie", 40, "Femme"),
(27, "Germain", "Guillaume", 41, "Homme"),
(28, "Deschamps", "Adeline", 42, "Femme"),
(29, "Blanc", "Michel", 43, "Homme"),
(30, "Girard", "Sylvie", 44, "Femme"),
(31, "Sauvage", "Jacqueline", 45, "Femme"),
(32, "David", "Laurent", 46, "Homme"),
(33, "Caron", "Monique", 47, "Femme"),
(34, "Hughes", "Alain", 48, "Homme"),
(35, "Deville", "Hélène", 49, "Femme"),
(36, "Dupuis", "Denis", 50, "Homme"),
(37, "Dufresne", "Marina", 51, "Femme"),
(38, "Dumas", "Céline", 52, "Femme"),
(39, "Richer", "Yannick", 53, "Homme"),
(40, "Vasseur", "Mathilde", 54, "Femme"),
(41, "Moulin", "Thierry", 55, "Homme"),
(42, "Schmitt", "Sophie", 56, "Femme"),
(43, "Robert", "Louis", 57, "Homme"),
(44, "Mauger", "Valérie", 58, "Femme"),
(45, "Benoit", "Marc", 59, "Homme"),
(46, "Tanguy", "Isabelle", 60, "Femme"),
(47, "Giraud", "Daniel", 45, "Homme"),
(48, "Lopez", "Laura", 36, "Femme"),
(49, "Renard", "Claude", 55, "Homme"),
(50, "Charpentier", "Anne", 48, "Femme");
(51, "Durand", "Lucas", 16, "Homme"),
(52, "Lemoine", "Chloé", 22, "Femme"),
(53, "Moreau", "Paul", 30, "Homme"),
(54, "Roux", "Claire", 25, "Femme"),
(55, "Lefevre", "Jean", 18, "Homme"),
(56, "Dupont", "Sophie", 23, "Femme"),
(57, "Thomas", "Michel", 33, "Homme"),
(58, "Perrin", "Isabelle", 27, "Femme"),
(59, "Barre", "Antoine", 40, "Homme"),
(60, "Fournier", "Caroline", 29, "Femme"),
(61, "Benoit", "Nicolas", 31, "Homme"),
(62, "Clement", "Élise", 21, "Femme"),
(63, "Gauthier", "Sébastien", 34, "Homme"),
(64, "Meyer", "Aurélie", 26, "Femme"),
(65, "Blanc", "Yannick", 44, "Homme"),
(66, "Leclerc", "Juliette", 19, "Femme"),
(67, "Girard", "Vincent", 38, "Homme"),
(68, "Deschamps", "Marion", 22, "Femme"),
(69, "Schmitt", "François", 47, "Homme"),
(70, "Lemoine", "Marc", 36, "Homme"),
(71, "Dupuis", "Laure", 41, "Femme"),
(72, "Moulin", "Éric", 28, "Homme"),
(73, "Richer", "Sophie", 32, "Femme"),
(74, "Germain", "Guillaume", 50, "Homme"),
(75, "Robert", "Monique", 56, "Femme"),
(76, "Foley", "Julien", 17, "Homme"),
(77, "Charpentier", "Lucie", 35, "Femme"),
(78, "Tanguy", "Marc", 60, "Homme"),
(79, "Boucher", "Aline", 25, "Femme"),
(80, "Caron", "David", 33, "Homme"),
(81, "Renard", "Caroline", 40, "Femme"),
(82, "Roux", "Michel", 22, "Homme"),
(83, "Vasseur", "Valérie", 48, "Femme"),
(84, "Meyer", "Sébastien", 24, "Homme"),
(85, "Leclerc", "Denis", 55, "Homme"),
(86, "Joly", "Jacques", 19, "Homme"),
(87, "Caron", "Mathilde", 21, "Femme"),
(88, "Dufresne", "Amandine", 26, "Femme"),
(89, "Sauvage", "Pierre", 39, "Homme"),
(90, "Vasseur", "Thierry", 45, "Homme"),
(91, "Benoit", "Martine", 52, "Femme"),
(92, "Thomas", "Antoine", 34, "Homme"),
(93, "Roux", "Virginie", 28, "Femme"),
(94, "Blanc", "Michel", 29, "Homme"),
(95, "Schmitt", "Sophie", 47, "Femme"),
(96, "Bernard", "Laurent", 49, "Homme"),
(97, "Tanguy", "Sophie", 30, "Femme"),
(98, "Dupont", "Vincent", 37, "Homme"),
(99, "Girard", "Christine", 31, "Femme"),
(100, "Dumas", "Julien", 18, "Homme");


INSERT INTO PERSONNALITE (id_personnalite, nom, prenom, metier) VALUES
INSERT INTO PERSONNE (nom, prenom, sexe, age, metier) VALUES
("DiCaprio", "Leonardo", "Homme", 49, "Acteur"),
("Depp", "Johnny", "Homme", 60, "Acteur"),
("Pitt", "Brad", "Homme", 60, "Acteur"),
("Jolie", "Angelina", "Femme", 49, "Actrice"),
("Kidman", "Nicole", "Femme", 56, "Actrice"),
("Washington", "Denzel", "Homme", 69, "Acteur"),
("Hanks", "Tom", "Homme", 67, "Acteur"),
("Lawrence", "Jennifer", "Femme", 33, "Actrice"),
("Streep", "Meryl", "Femme", 74, "Actrice"),
("Johansson", "Scarlett", "Femme", 39, "Actrice"),
("Spielberg", "Steven", "Homme", 77, "Réalisateur"),
("Nolan", "Christopher", "Homme", 53, "Réalisateur"),
("Scorsese", "Martin", "Homme", 81, "Réalisateur"),
("Tarantino", "Quentin", "Homme", 61, "Réalisateur"),
("Kubrick", "Stanley", "Homme", 70, "Réalisateur"),
("Coppola", "Francis Ford", "Homme", 84, "Réalisateur"),
("Bigelow", "Kathryn", "Femme", 72, "Réalisatrice"),
("Villeneuve", "Denis", "Homme", 56, "Réalisateur"),
("Burton", "Tim", "Homme", 65, "Réalisateur"),
("Anderson", "Wes", "Homme", 54, "Réalisateur"),
("Jackson", "Peter", "Homme", 62, "Réalisateur"),
("Lucas", "George", "Homme", 80, "Producteur"),
("Abrams", "J.J.", "Homme", 57, "Producteur"),
("Feige", "Kevin", "Homme", 50, "Producteur"),
("Cameron", "James", "Homme", 69, "Producteur"),
("Kennedy", "Kathleen", "Femme", 70, "Productrice"),
("Bruckheimer", "Jerry", "Homme", 80, "Producteur"),
("Zanuck", "Richard", "Homme", 77, "Producteur"),
("Broccoli", "Barbara", "Femme", 63, "Productrice"),
("Blum", "Jason", "Homme", 54, "Producteur"),
("Winslet", "Kate", "Femme", 48, "Actrice"),
("Blanchett", "Cate", "Femme", 54, "Actrice"),
("Davis", "Viola", "Femme", 58, "Actrice"),
("Hemsworth", "Chris", "Homme", 40, "Acteur"),
("Evans", "Chris", "Homme", 42, "Acteur"),
("Downey Jr.", "Robert", "Homme", 58, "Acteur"),
("Ruffalo", "Mark", "Homme", 56, "Acteur"),
("Hathaway", "Anne", "Femme", 41, "Actrice"),
("Clooney", "George", "Homme", 62, "Acteur"),
("Bale", "Christian", "Homme", 49, "Acteur"),
("Pacino", "Al", "Homme", 83, "Acteur"),
("De Niro", "Robert", "Homme", 80, "Acteur"),
("Theron", "Charlize", "Femme", 48, "Actrice"),
("Portman", "Natalie", "Femme", 42, "Actrice"),
("Waltz", "Christoph", "Homme", 67, "Acteur"),
("Hardy", "Tom", "Homme", 46, "Acteur"),
("Phoenix", "Joaquin", "Homme", 49, "Acteur"),
("Gosling", "Ryan", "Homme", 43, "Acteur"),
("Chastain", "Jessica", "Femme", 46, "Actrice"),
("Anderson", "Paul Thomas", "Homme", 53, "Réalisateur"),
("Hitchcock", "Alfred", "Homme", 80, "Réalisateur"),
("Fincher", "David", "Homme", 61, "Réalisateur"),
("Lee", "Ang", "Homme", 69, "Réalisateur"),
("Del Toro", "Guillermo", "Homme", 59, "Réalisateur"),
("Coen", "Ethan", "Homme", 66, "Réalisateur"),
("Coen", "Joel", "Homme", 69, "Réalisateur"),
("Eastwood", "Clint", "Homme", 93, "Réalisateur"),
("Leigh", "Mike", "Homme", 80, "Réalisateur"),
("Almodóvar", "Pedro", "Homme", 74, "Réalisateur"),
("Ledger", "Heath", "Homme", 28, "Acteur"),
("McKellen", "Ian", "Homme", 84, "Acteur"),
("Blunt", "Emily", "Femme", 40, "Actrice"),
("Thompson", "Emma", "Femme", 64, "Actrice"),
("Hopkins", "Anthony", "Homme", 86, "Acteur"),
("Mirren", "Helen", "Femme", 78, "Actrice"),
("Smith", "Will", "Homme", 55, "Acteur"),
("Craig", "Daniel", "Homme", 55, "Acteur"),
("Larson", "Brie", "Femme", 34, "Actrice"),
("Radcliffe", "Daniel", "Homme", 35, "Acteur"),
("Stone", "Emma", "Femme", 35, "Actrice"),
("Bay", "Michael", "Homme", 59, "Producteur"),
("Marshall", "Frank", "Homme", 77, "Producteur"),
("Kennedy", "Kathleen", "Femme", 70, "Productrice"),
("Abrams", "J.J.", "Homme", 57, "Réalisateur"),
("Bigelow", "Kathryn", "Femme", 72, "Réalisatrice"),
("Cameron", "James", "Homme", 69, "Réalisateur"),
("Lucas", "George", "Homme", 80, "Producteur"),
("Ritchie", "Guy", "Homme", 55, "Réalisateur"),
("Villeneuve", "Denis", "Homme", 56, "Réalisateur"),
("Burton", "Tim", "Homme", 65, "Réalisateur"),
("Anderson", "Wes", "Homme", 54, "Réalisateur"),
("Spielberg", "Steven", "Homme", 77, "Réalisateur"),
("Scott", "Ridley", "Homme", 86, "Réalisateur"),
("Howard", "Ron", "Homme", 70, "Réalisateur"),
("Fincher", "David", "Homme", 61, "Réalisateur"),
("Coen", "Ethan", "Homme", 66, "Réalisateur"),
("Coen", "Joel", "Homme", 69, "Réalisateur"),
("Zanuck", "Richard", "Homme", 77, "Producteur"),
("Broccoli", "Barbara", "Femme", 63, "Productrice"),
("Bruckheimer", "Jerry", "Homme", 80, "Producteur"),
("Whedon", "Joss", "Homme", 59, "Producteur"),
("Blum", "Jason", "Homme", 54, "Producteur"),
("Eastwood", "Clint", "Homme", 93, "Réalisateur"),
("Almodóvar", "Pedro", "Homme", 74, "Réalisateur"),
("Del Toro", "Guillermo", "Homme", 59, "Réalisateur"),
("Hitchcock", "Alfred", "Homme", 80, "Réalisateur"),
("Nolan", "Christopher", "Homme", 53, "Réalisateur"),
("Tarantino", "Quentin", "Homme", 61, "Réalisateur"),
("Reitman", "Ivan", "Homme", 75, "Producteur"),
("Smith", "Kevin", "Homme", 53, "Réalisateur"),
("Zemeckis", "Robert", "Homme", 72, "Réalisateur"),
("Stone", "Oliver", "Homme", 77, "Réalisateur"),
("Affleck", "Ben", "Homme", 51, "Réalisateur"),
("Scorsese", "Martin", "Homme", 81, "Réalisateur"),
("Dee", "Ruby", "Femme", 80, "Productrice"),
("Peele", "Jordan", "Homme", 44, "Réalisateur"),
("Waititi", "Taika", "Homme", 48, "Réalisateur"),
("Gerwig", "Greta", "Femme", 40, "Réalisatrice"),
("Jenkins", "Patty", "Femme", 52, "Réalisatrice"),
("Chazelle", "Damien", "Homme", 39, "Réalisateur"),
("Raimi", "Sam", "Homme", 64, "Réalisateur"),
("Kosinski", "Joseph", "Homme", 49, "Réalisateur"),
("Scott", "Tony", "Homme", 68, "Réalisateur"),
("Bong", "Joon-ho", "Homme", 54, "Réalisateur"),
("Kurosawa", "Akira", "Homme", 88, "Réalisateur"),
("Miyazaki", "Hayao", "Homme", 82, "Réalisateur"),
("Lasseter", "John", "Homme", 66, "Producteur"),
("Pixar", "John", "Homme", 72, "Producteur"),
("Anderson", "Paul W.S.", "Homme", 58, "Réalisateur"),
("Verhoeven", "Paul", "Homme", 85, "Réalisateur"),
("Tykwer", "Tom", "Homme", 58, "Réalisateur"),
("Weir", "Peter", "Homme", 79, "Réalisateur"),
("Boyle", "Danny", "Homme", 67, "Réalisateur"),
("Gondry", "Michel", "Homme", 60, "Réalisateur"),
("Forman", "Milos", "Homme", 86, "Réalisateur"),
("Reed", "Peyton", "Homme", 59, "Réalisateur"),
("McTiernan", "John", "Homme", 72, "Réalisateur"),
("Coogler", "Ryan", "Homme", 37, "Réalisateur"),
("Miller", "George", "Homme", 78, "Réalisateur"),
("Anderson", "Roy", "Homme", 80, "Réalisateur");
