--JEUX DE DONNEES LANGUE--
INSERT INTO LANGUE (code, nom_langue) VALUES
( 'FR', 'Français'),
( 'EN', 'Anglais'),
( 'ES', 'Espagnol'),
( 'DE', 'Allemand'),
( 'IT', 'Italien'),
( 'PT', 'Portugais'),
( 'RU', 'Russe'),
( 'ZH', 'Chinois (Mandarin)'),
('JA', 'Japonais'),
( 'KO', 'Coréen'),
( 'AR', 'Arabe'),
( 'HI', 'Hindi'),
('BE', 'Bengali'),
( 'PA', 'Punjabi'),
( 'UR', 'Ourdou'),
( 'TR', 'Turc'),
( 'PL', 'Polonais'),
( 'NL', 'Néerlandais'),
( 'SV', 'Suédois'),
( 'NO', 'Norvégien'),
( 'DA', 'Danois'),
( 'FI', 'Finnois'),
( 'CS', 'Tchèque'),
( 'EL', 'Grec'),
( 'HE', 'Hébreu'),
( 'TH', 'Thaïlandais'),
( 'ID', 'Indonésien'),
( 'MS', 'Malais'),
( 'VI', 'Vietnamien'),
( 'SW', 'Swahili');

--JEUX DE DONNEES CATEGORIE--
INSERT INTO CATEGORIE (id_categorie, genre) VALUES
(1, "Action"),
(2, "Aventure"),
(3, "Comédie"),
(4, "Drame"),
(5, "Science-fiction"),
(6, "Fantastique"),
(7, "Horreur"),
(8, "Thriller"),
(9, "Romance"),
(10, "Animation"),
(11, "Documentaire"),
(12, "Policier"),
(13, "Historique"),
(14, "Musical"),
(15, "Mystère"),
(16, "Guerre"),
(17, "Western"),
(18, "Familial"),
(19, "Biographique"),
(20, "Sport"),
(21, "Crime"),
(22, "Anecdote"),
(23, "Film noir"),
(24, "Fantasy"),
(25, "Epouvante"),
(26, "Suspense"),
(27, "Parodie"),
(28, "Satire"),
(29, "LGBTQ+"),
(30, "Drame psychologique");



--JEUX DE DONNEES SPECTATEURS--
INSERT INTO SPECTATEUR (id_spectateur, nom, prenom, age, sexe) VALUES
(1, "Dupond", "Jean", 15, "Homme"),
(2, "Martin", "Claire", 16, "Femme"),
(3, "Lemoine", "Paul", 17, "Homme"),
(4, "Durand", "Sophie", 18, "Femme"),
(5, "Moreau", "Luc", 19, "Homme"),
(6, "Lefevre", "Isabelle", 20, "Femme"),
(7, "Roux", "Michel", 21, "Homme"),
(8, "Perrin", "Juliette", 22, "Femme"),
(9, "Gauthier", "Pierre", 23, "Homme"),
(10, "Clement", "Nathalie", 24, "Femme"),
(11, "Meyer", "Jean-Pierre", 25, "Homme"),
(12, "Bernard", "Chantal", 26, "Femme"),
(13, "Simon", "Jacques", 27, "Homme"),
(14, "Barre", "Elise", 28, "Femme"),
(15, "Boucher", "Thomas", 29, "Homme"),
(16, "Robert", "Emilie", 30, "Femme"),
(17, "Joly", "Victor", 31, "Homme"),
(18, "Benoit", "Aline", 32, "Femme"),
(19, "Lemoine", "Marc", 33, "Homme"),
(20, "Fournier", "Carole", 34, "Femme"),
(21, "Thomas", "Antoine", 35, "Homme"),
(22, "Vincent", "Sabrina", 36, "Femme"),
(23, "Leclerc", "Denis", 37, "Homme"),
(24, "Lemoine", "Sandrine", 38, "Femme"),
(25, "Brunet", "Georges", 39, "Homme"),
(26, "Chauvin", "Mélanie", 40, "Femme"),
(27, "Germain", "Guillaume", 41, "Homme"),
(28, "Deschamps", "Adeline", 42, "Femme"),
(29, "Blanc", "Michel", 43, "Homme"),
(30, "Girard", "Sylvie", 44, "Femme"),
(31, "Sauvage", "Jacqueline", 45, "Femme"),
(32, "David", "Laurent", 46, "Homme"),
(33, "Caron", "Monique", 47, "Femme"),
(34, "Hughes", "Alain", 48, "Homme"),
(35, "Deville", "Hélène", 49, "Femme"),
(36, "Dupuis", "Denis", 50, "Homme"),
(37, "Dufresne", "Marina", 51, "Femme"),
(38, "Dumas", "Céline", 52, "Femme"),
(39, "Richer", "Yannick", 53, "Homme"),
(40, "Vasseur", "Mathilde", 54, "Femme"),
(41, "Moulin", "Thierry", 55, "Homme"),
(42, "Schmitt", "Sophie", 56, "Femme"),
(43, "Robert", "Louis", 57, "Homme"),
(44, "Mauger", "Valérie", 58, "Femme"),
(45, "Benoit", "Marc", 59, "Homme"),
(46, "Tanguy", "Isabelle", 60, "Femme"),
(47, "Giraud", "Daniel", 45, "Homme"),
(48, "Lopez", "Laura", 36, "Femme"),
(49, "Renard", "Claude", 55, "Homme"),
(50, "Charpentier", "Anne", 48, "Femme");
(51, "Durand", "Lucas", 16, "Homme"),
(52, "Lemoine", "Chloé", 22, "Femme"),
(53, "Moreau", "Paul", 30, "Homme"),
(54, "Roux", "Claire", 25, "Femme"),
(55, "Lefevre", "Jean", 18, "Homme"),
(56, "Dupont", "Sophie", 23, "Femme"),
(57, "Thomas", "Michel", 33, "Homme"),
(58, "Perrin", "Isabelle", 27, "Femme"),
(59, "Barre", "Antoine", 40, "Homme"),
(60, "Fournier", "Caroline", 29, "Femme"),
(61, "Benoit", "Nicolas", 31, "Homme"),
(62, "Clement", "Élise", 21, "Femme"),
(63, "Gauthier", "Sébastien", 34, "Homme"),
(64, "Meyer", "Aurélie", 26, "Femme"),
(65, "Blanc", "Yannick", 44, "Homme"),
(66, "Leclerc", "Juliette", 19, "Femme"),
(67, "Girard", "Vincent", 38, "Homme"),
(68, "Deschamps", "Marion", 22, "Femme"),
(69, "Schmitt", "François", 47, "Homme"),
(70, "Lemoine", "Marc", 36, "Homme"),
(71, "Dupuis", "Laure", 41, "Femme"),
(72, "Moulin", "Éric", 28, "Homme"),
(73, "Richer", "Sophie", 32, "Femme"),
(74, "Germain", "Guillaume", 50, "Homme"),
(75, "Robert", "Monique", 56, "Femme"),
(76, "Foley", "Julien", 17, "Homme"),
(77, "Charpentier", "Lucie", 35, "Femme"),
(78, "Tanguy", "Marc", 60, "Homme"),
(79, "Boucher", "Aline", 25, "Femme"),
(80, "Caron", "David", 33, "Homme"),
(81, "Renard", "Caroline", 40, "Femme"),
(82, "Roux", "Michel", 22, "Homme"),
(83, "Vasseur", "Valérie", 48, "Femme"),
(84, "Meyer", "Sébastien", 24, "Homme"),
(85, "Leclerc", "Denis", 55, "Homme"),
(86, "Joly", "Jacques", 19, "Homme"),
(87, "Caron", "Mathilde", 21, "Femme"),
(88, "Dufresne", "Amandine", 26, "Femme"),
(89, "Sauvage", "Pierre", 39, "Homme"),
(90, "Vasseur", "Thierry", 45, "Homme"),
(91, "Benoit", "Martine", 52, "Femme"),
(92, "Thomas", "Antoine", 34, "Homme"),
(93, "Roux", "Virginie", 28, "Femme"),
(94, "Blanc", "Michel", 29, "Homme"),
(95, "Schmitt", "Sophie", 47, "Femme"),
(96, "Bernard", "Laurent", 49, "Homme"),
(97, "Tanguy", "Sophie", 30, "Femme"),
(98, "Dupont", "Vincent", 37, "Homme"),
(99, "Girard", "Christine", 31, "Femme"),
(100, "Dumas", "Julien", 18, "Homme");


INSERT INTO PERSONNALITE (id_personnalite, nom, prenom, metier) VALUES
(1, "DiCaprio", "Leonardo", "Acteur"),
(2, "Depp", "Johnny", "Acteur"),
(3, "Pitt", "Brad", "Acteur"),
(4, "Jolie", "Angelina", "Actrice"),
(5, "Kidman", "Nicole", "Actrice"),
(6, "Washington", "Denzel", "Acteur"),
(7, "Hanks", "Tom", "Acteur"),
(8, "Lawrence", "Jennifer", "Actrice"),
(9, "Streep", "Meryl", "Actrice"),
(10, "Johansson", "Scarlett", "Actrice"),
(11, "Spielberg", "Steven", "Réalisateur"),
(12, "Nolan", "Christopher", "Réalisateur"),
(13, "Scorsese", "Martin", "Réalisateur"),
(14, "Tarantino", "Quentin", "Réalisateur"),
(15, "Kubrick", "Stanley", "Réalisateur"),
(16, "Coppola", "Francis Ford", "Réalisateur"),
(17, "Bigelow", "Kathryn", "Réalisatrice"),
(18, "Villeneuve", "Denis", "Réalisateur"),
(19, "Burton", "Tim", "Réalisateur"),
(20, "Anderson", "Wes", "Réalisateur"),
(21, "Jackson", "Peter", "Réalisateur"),
(22, "Lucas", "George", "Producteur"),
(23, "Abrams", "J.J.", "Producteur"),
(24, "Feige", "Kevin", "Producteur"),
(25, "Cameron", "James", "Producteur"),
(26, "Kennedy", "Kathleen", "Productrice"),
(27, "Bruckheimer", "Jerry", "Producteur"),
(28, "Zanuck", "Richard", "Producteur"),
(29, "Broccoli", "Barbara", "Productrice"),
(30, "Blum", "Jason", "Producteur"),
(31, "Winslet", "Kate", "Actrice"),
(32, "Blanchett", "Cate", "Actrice"),
(33, "Davis", "Viola", "Actrice"),
(34, "Hemsworth", "Chris", "Acteur"),
(35, "Evans", "Chris", "Acteur"),
(36, "Downey Jr.", "Robert", "Acteur"),
(37, "Ruffalo", "Mark", "Acteur"),
(38, "Hathaway", "Anne", "Actrice"),
(39, "Clooney", "George", "Acteur"),
(40, "Bale", "Christian", "Acteur"),
(41, "Pacino", "Al", "Acteur"),
(42, "De Niro", "Robert", "Acteur"),
(43, "Theron", "Charlize", "Actrice"),
(44, "Portman", "Natalie", "Actrice"),
(45, "Winslet", "Kate", "Actrice"),
(46, "Waltz", "Christoph", "Acteur"),
(47, "Hardy", "Tom", "Acteur"),
(48, "Phoenix", "Joaquin", "Acteur"),
(49, "Gosling", "Ryan", "Acteur"),
(50, "Chastain", "Jessica", "Actrice"),
(51, "Anderson", "Paul Thomas", "Réalisateur"),
(52, "Hitchcock", "Alfred", "Réalisateur"),
(53, "Fincher", "David", "Réalisateur"),
(54, "Lee", "Ang", "Réalisateur"),
(55, "Del Toro", "Guillermo", "Réalisateur"),
(56, "Coen", "Ethan", "Réalisateur"),
(57, "Coen", "Joel", "Réalisateur"),
(58, "Eastwood", "Clint", "Réalisateur"),
(59, "Leigh", "Mike", "Réalisateur"),
(60, "Almodóvar", "Pedro", "Réalisateur"),
(61, "Whedon", "Joss", "Producteur"),
(62, "Reitman", "Ivan", "Producteur"),
(63, "Silver", "Joel", "Producteur"),
(64, "Bay", "Michael", "Producteur"),
(65, "Howard", "Ron", "Producteur"),
(66, "Nair", "Mira", "Productrice"),
(67, "Marshall", "Frank", "Producteur"),
(68, "Ritchie", "Guy", "Producteur"),
(69, "Anderson", "Paul W.S.", "Producteur"),
(70, "Smith", "Kevin", "Producteur"),
(71, "Larson", "Brie", "Actrice"),
(72, "Gyllenhaal", "Jake", "Acteur"),
(73, "Reeves", "Keanu", "Acteur"),
(74, "Pine", "Chris", "Acteur"),
(75, "Affleck", "Ben", "Acteur"),
(76, "Stone", "Emma", "Actrice"),
(77, "Roberts", "Julia", "Actrice"),
(78, "Watson", "Emma", "Actrice"),
(79, "Radcliffe", "Daniel", "Acteur"),
(80, "Grint", "Rupert", "Acteur"),
(81, "Olsen", "Elizabeth", "Actrice"),
(82, "Zellweger", "Renée", "Actrice"),
(83, "Ledger", "Heath", "Acteur"),
(84, "McKellen", "Ian", "Acteur"),
(85, "Blunt", "Emily", "Actrice"),
(86, "Thompson", "Emma", "Actrice"),
(87, "Fiennes", "Ralph", "Acteur"),
(88, "Hopkins", "Anthony", "Acteur"),
(89, "Mirren", "Helen", "Actrice"),
(90, "Day-Lewis", "Daniel", "Acteur"),
(91, "Hawke", "Ethan", "Acteur"),
(92, "Tatum", "Channing", "Acteur"),
(93, "Brosnan", "Pierce", "Acteur"),
(94, "Berry", "Halle", "Actrice"),
(95, "Craig", "Daniel", "Acteur"),
(96, "Ferrell", "Will", "Acteur"),
(97, "Damon", "Matt", "Acteur"),
(98, "Johnson", "Dwayne", "Acteur"),
(99, "Smith", "Will", "Acteur"),
(100, "Washington", "Kerry", "Actrice"),
(101, "Winslet", "Kate", "Actrice");

